# Generated by Django 5.1.5 on 2025-01-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='converted_type',
            field=models.CharField(choices=[('JSON', 'JSON Document'), ('CSV', 'CSV Document'), ('TXT', 'TXT Document'), ('HTML', 'HTML Document'), ('PDF', 'PDF Document'), ('PNG', 'PNG Document'), ('JPEG', 'JPEG Document'), ('JPG', 'JPG Document')], max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_type',
            field=models.CharField(choices=[('JSON', 'JSON Document'), ('CSV', 'CSV Document'), ('TXT', 'TXT Document'), ('HTML', 'HTML Document'), ('PDF', 'PDF Document'), ('PNG', 'PNG Document'), ('JPEG', 'JPEG Document'), ('JPG', 'JPG Document')], max_length=255),
        ),
    ]
