# Generated by Django 5.1.5 on 2025-02-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_document_converted_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='converted_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='original_type',
        ),
    ]
