# Generated by Django 5.1.5 on 2025-02-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_converted_type_document_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.URLField(default='https://example.com'),
        ),
    ]
