# Generated by Django 5.1.5 on 2025-02-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_document_options_alter_log_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
