# Generated by Django 5.1.5 on 2025-02-03 07:27

import django.template.defaulttags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_document_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=django.template.defaulttags.now),
        ),
    ]
