# Generated by Django 5.1.6 on 2025-02-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_log_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.FileField(upload_to='store/documents'),
        ),
    ]
