# Generated by Django 5.1.6 on 2025-02-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_document_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='store/documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
